name: Appinspect workflow

on:
  workflow_call:
    secrets:
      API_USER:
        required: true
      API_PASS:
        required: true

jobs:
  appinspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Download packaging toolkit
        run: wget https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Install packaging toolkit
        run: pip install splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Package app
        run: |
          cd src
          slim package -o ~/build/packages $(ls)
      - name: Download and run appinspect script
        run: |
          cd ~/build/packages
          curl -sSL https://raw.githubusercontent.com/ZachChristensen28/splunk-app-dev/511c3b4b5fcfeabaeb93d5c8d9842c3b0aa28736/appinspect.sh | API_USER='${{ secrets.API_USER }}' API_PASS='${{ secrets.API_PASS }}' APP_PATH=$(ls) bash
      - name: Collect report
        uses: actions/upload-artifact@v3
        with:
          name: Appinspect-report
          path: ~/reports/
      - name: Collect app package
        uses: actions/upload-artifact@v3
        with:
          name: App-package
          path: ~/build/packages/
