name: Increment Build Number Workflow

on:
  workflow_call:

jobs:
  increment-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: increment build number
        run: |
          n=$(egrep "^build" src/*/default/app.conf | awk '{ print $3 }')
          build_number=$((n+1))
          sed -i "s/build = \w/build = $build_number/" src/*/default/app.conf
      - name: collect branch name
        id: branch_name
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "increment build version"
          branch: ${{ steps.branch_name.outputs.branch }}
